In [6]:
import torch

In [7]:
# Tensor attributes
t1 = torch.tensor([1,2,3])
print(t1.dim(), t1.shape)

1 torch.Size([3])


In [10]:
t2 = torch.tensor(
    [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10,11,12]
    ]
)
print("Number of axes/dimensions/indixes required to access an element ", t2.dim())
print(t2)

Number of axes/dimensions/indixes required to access an element  2
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [ ]:
# Begin Reshaping operations Section

In [20]:
# Using reshape()
t3 = t2.reshape((2,6))
t3.shape, t3.dim(), t3.numel()

(torch.Size([2, 6]), 2, 12)

In [13]:
# Using view()
t2.view((1,12))

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [17]:
# Using unsqueeze() to add a new dimension of rank1 at the specified dim

t = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
])
t0_unsq = t.unsqueeze(dim=0)
t1_unsq = t.unsqueeze(dim=1)
print(t0_unsq, t0_unsq.shape, "\n")
print(t1_unsq, t1_unsq.shape)


tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]]) torch.Size([1, 2, 4]) 

tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]]) torch.Size([2, 1, 4])


In [20]:
# Use squeeze to remove all length 1  dimensions
t = torch.rand(3,4)

# Shape (1,1,12)
tz = t.reshape(1,1,12)
print("Before unsqueeze", tz, "\n")

tz1 = tz.squeeze()

# Shape [12]
print("After unsqueeze", tz1, tz1.shape, "\n")


Before unsqueeze tensor([[[0.0973, 0.8002, 0.5463, 0.9779, 0.5315, 0.6094, 0.3179, 0.4331,
          0.6416, 0.1813, 0.9285, 0.4356]]]) 

After unsqueeze tensor([0.0973, 0.8002, 0.5463, 0.9779, 0.5315, 0.6094, 0.3179, 0.4331, 0.6416,
        0.1813, 0.9285, 0.4356]) torch.Size([12]) 



In [24]:
# Use flatten to reduce dimensions
a = torch.rand(2,3,4)
print("Before flatten ",a, a.shape, "\n")
a_flat = a.flatten(start_dim=1)
print("After flatten ",a_flat, a_flat.shape, "\n")

Before flatten  tensor([[[0.1138, 0.2805, 0.8692, 0.0478],
         [0.6811, 0.2091, 0.4056, 0.7155],
         [0.5528, 0.3131, 0.6136, 0.7211]],

        [[0.1093, 0.3562, 0.2891, 0.3517],
         [0.7930, 0.8745, 0.0818, 0.4835],
         [0.3295, 0.8563, 0.8852, 0.7181]]]) torch.Size([2, 3, 4]) 

After flatten  tensor([[0.1138, 0.2805, 0.8692, 0.0478, 0.6811, 0.2091, 0.4056, 0.7155, 0.5528,
         0.3131, 0.6136, 0.7211],
        [0.1093, 0.3562, 0.2891, 0.3517, 0.7930, 0.8745, 0.0818, 0.4835, 0.3295,
         0.8563, 0.8852, 0.7181]]) torch.Size([2, 12]) 



In [29]:
# Use cat to concat tensors
a = [[1,2],[3,4]]
b= [[5,6],[7,8]]
t1 = torch.tensor(a)
t2 = torch.tensor(b)

t_concat0 = torch.cat((t1,t2), dim=0)
print("Concat along first dim\n ",t_concat0, "\n")

t_concat1 = torch.cat((t1,t2), dim=1)
print("Concat along second dim\n", t_concat1)



Concat along first dim
  tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 

Concat along second dim
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
# End of Reshaping operations


In [ ]:
# Begin Element Wise Operations

In [30]:
# Arithmetic operations
a = [[1,2],
     [3,4]
    ]
b = [[5,6],
     [7,8]
    ]

t1 = torch.tensor(a)
t2 = torch.tensor(b)

print("\n t1+t2 \n", t1+t2)
print("\n t1+5 \n", t1+5)




 t1+t2 
 tensor([[ 6,  8],
        [10, 12]])

 t1+5 
 tensor([[6, 7],
        [8, 9]])


In [32]:
# Broadcast Example
t3 = torch.tensor([4,8])
# t3 is broadcasted as [[4,8],[4,8]] to match  T1 shape 
t1+t3

tensor([[ 5, 10],
        [ 7, 12]])

In [47]:
# Comparision operations
a = [[1,2],
     [1,4]
    ]
t = torch.tensor(a)
print("\n ", t.eq(1), "\n")
print("\n ", t.lt(7), "\n")


  tensor([[ True, False],
        [ True, False]]) 


  tensor([[True, True],
        [True, True]]) 



In [ ]:
# End Element Wise Operations

In [ ]:
# Begin Reduction Operations

In [49]:
a = [[1,2],
     [1,4]
    ]
t = torch.tensor(a)
print("All elements sum ", t.sum(), "\n")
print("sum along first dim ", t.sum(dim=0), "\n")
print("sum along second dim", t.sum(dim=1), "\n")


All elements sum  tensor(8) 

sum aong first dim  tensor([2, 6]) 

sum along second dim tensor([3, 5]) 



In [52]:
b = [[1,2,3,9],
     [-1,0,1,4],
     [10, 1,6,7]
    ]
t = torch.tensor(b)
print("\n Overall max \n", t.max())
print("\n Overall arg max \n", t.argmax())
print("\n max along dim 0 \n", t.max(dim=0))
print("\n argmax along dim 0 \n", t.argmax(dim=0))
print("\n max along dim 1 \n", t.max(dim=1))
print("\n argmax along dim 1 \n", t.argmax(dim=1))



 Overall max 
 tensor(10)

 Overall arg max 
 tensor(8)

 max along dim 0 
 torch.return_types.max(
values=tensor([10,  2,  6,  9]),
indices=tensor([2, 0, 2, 0]))

 argmax along dim 0 
 tensor([2, 0, 2, 0])

 max along dim 1 
 torch.return_types.max(
values=tensor([ 9,  4, 10]),
indices=tensor([3, 3, 0]))

 argmax along dim 1 
 tensor([3, 3, 0])


In [53]:
# Indexes
a = [[1,2,3,4],[5,6,7,8]]
t = torch.tensor(a)
t[t%2==1]

tensor([1, 3, 5, 7])

In [2]:
import torch
x = torch.randn(128,64,1,1)
x.shape

torch.Size([128, 64, 1, 1])