In [1]:
import torch
import numpy as np

In [5]:
# Tensor attributes
# Most important are rank and shape
a = torch.Tensor([[1,2,3],[4,5,6]])
print("Dimensions ", a.dim())
print("Shape ", a.shape)
print("Number of el ", a.numel())


# For a specific axis
print(a[0].dim())
print(a[0].shape)
print(a[0].numel())

Dimensions  2
Shape  torch.Size([2, 3])
Number of el  6
1
torch.Size([3])
3


In [16]:
# Create Tensor
a = np.array([[1,2,3],[4,5,6]])
# Option1
t1 = torch.Tensor(a)
print("Option 1\n", t1, "\n")

# Option2 : 
# Automatic type inference
t2 = torch.tensor(a)
print("Option 2\n", t2, "\n")

# Option3:
# Automatic type inference
# Deep copy of numpy array a
t3 = torch.as_tensor(a)
print("Option 3\n", t3, "\n")

a[0][2]  = 5  # t3 is updated
print("After update\n ", t3, "\n")

Option 1
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

Option 2
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) 

Option 3
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) 

After update
  tensor([[1, 2, 5],
        [4, 5, 6]], dtype=torch.int32) 



In [21]:
# Other Tensor creations
a = torch.ones((3,4), dtype = torch.float32)
b = torch.zeros((3,4))
print(a,"\n", b)

# Using the same data type as existing tensor using new_ones()
c = a.new_ones((5,6))
print("New ones \n", c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
New ones 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [51]:
# Tensor Modification Operations
# 1.reshape()
# 2.view() . Similar to reshape but works only on contigous shapes
# 3.squeeze()
# 4.unsqueeze()
# 5.flatten()
# 6.cat()
# 7. permute()


# Reshape Operations
# Org shape : 3x4
t = torch.tensor([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
print("Original tensor t \n", t)

# Change the shape but keep the dimensions same
t1 = t.reshape((2,6))
print("t1 \n ", t1)

# Change the shape and change the dimensions to 3
t2 = t.reshape((2,3,2))
print("t2 \n ", t2, t2.dim())



# Concat
t6 = torch.tensor([
    [1,2],
    [3,4]])
t7 = torch.tensor([
    [1,2],
    [3,4]])

t8 = torch.cat((t6,t7), dim=0)
print("Concat along zero dimension \n", t8)

t9 = torch.cat((t6,t7), dim=1)
print("Concat along 1st dimension \n", t9)


Original tensor t 
 tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
t1 
  tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]])
t2 
  tensor([[[1, 1],
         [1, 1],
         [2, 2]],

        [[2, 2],
         [3, 3],
         [3, 3]]]) 3
t3 
 tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])
tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]]) torch.Size([1, 3, 4])
Flattened tensor 
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
Concat along zero dimension 
 tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])
Concat along 1st dimension 
 tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])


In [84]:
# Flatten
# This operation flattens an nd tensor to 1 dimension
t = torch.ones(3,4).reshape(2,3,2)
print("\n orig tensor \n ", t)

t5 = t.flatten()# defaults to 0 as starting dimension to flatten
print("\n Tensor flattened at dim 0  \n", t5) # One row of all 1

t6 = t.flatten(1)
print("\n Tensor flattened at dim 1 \n", t6)  # 2 rows of all 1



 orig tensor 
  tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

 Tensor flattened at dim 0  
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

 Tensor flattened at dim 1 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [88]:
# Squeeze
# This removes all the len(1) dimensions
# Does not require dimension as parameter
# Wont have any impact on len>1 dimensions
t = torch.tensor([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
print("\n Orginal tensor t \n", t)

t3 = t.reshape((1,12)).squeeze()
print("\n t3 \n", t3)

# Unsqueeze
# this adds a dimension along the specified axis
t4 = t.unsqueeze(dim=0)  # Transforms (3,4) -> (1,3,4)
print("\n t4 \n ", t4, t4.shape)



 Orginal tensor t 
 tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

 t3 
 tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

 t4 
  tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]]]) torch.Size([1, 3, 4])


In [110]:
# Broadcast
# Key Concept: Broadcast happens to match shapes
# Eg: Tensor + 2 => In this case 2 is reshaped to a tensor of 2's of the same shape as Tensor

a = torch.tensor([[1,2,3], [4,6,11]], dtype = torch.float32)
mul_result = a*2
print("Element wise multiplication \n ", mul_result)

add_result = a+3
print("Element wise addition \n ", add_result)




# Single Tensor Operation

# Sum all elements
sum_result = a.sum()
print("Sum result \n ",sum_result)

# Sum along a given axis
col_sum_result = torch.sum(a, dim=0) # col sum
print("Axis row result dim 0 \n ", col_sum_result)  #[5,8,14]

row_sum_result = torch.sum(a, dim=1) # Row sum
print("Axis row result dim 1 \n ", row_sum_result)  #[[6], [21]]


# Check conditions
condition_result = a.le(8)
print("\n Condition result \n", condition_result)


foo = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,10]
], dtype = torch.float32)

# Mean
print("\n Mean \n", foo.mean())  # Tensor(5)
# item() returns the scalar value as a number instead of tensor
print("\n Mean \n", foo.mean().item())  # 5

# Arg max returns the index of max val
print("\n Max el \n", foo.argmax())
print("\n Max el for a given axis \n", a.argmax(dim=1))




Element wise multiplication 
  tensor([[ 2.,  4.,  6.],
        [ 8., 12., 22.]])
Element wise addition 
  tensor([[ 4.,  5.,  6.],
        [ 7.,  9., 14.]])
Sum result 
  tensor(27.)
Axis row result dim 0 
  tensor([ 5.,  8., 14.])
Axis row result dim 1 
  tensor([ 6., 21.])

 Condition result 
 tensor([[ True,  True,  True],
        [ True,  True, False]])

 Mean 
 tensor(5.1111)

 Mean 
 5.111111164093018

 Max el 
 tensor(8)

 Max el for a given axis 
 tensor([2, 2])


In [98]:
foo = torch.tensor([1,2,3])

# List comprehension
bar = torch.tensor([1 if i%2==0 else 0 for i in foo])
print(" \n List comprehension \n", bar)
# User defined function
def add_10(x):
    return x+10

baz = torch.tensor([add_10(i) for i in foo])
print(" \n User defined function \n", baz)

 
 List comprehension 
 tensor([0, 1, 0])
 
 User defined function 
 tensor([11, 12, 13])


In [99]:
a = torch.tensor([ [1,2,3,4], [5,6,7,8]])
print(a.shape)
a1 = a.reshape((1,1,8))
print(a1, a1.dim())
b = a1.squeeze()
print(b,  b.dim())
c = b.unsqueeze(dim=-2)
d = b.unsqueeze(dim=0)
print(c, c.dim())
print(d, d.dim())

torch.Size([2, 4])
tensor([[[1, 2, 3, 4, 5, 6, 7, 8]]]) 3
tensor([1, 2, 3, 4, 5, 6, 7, 8]) 1
tensor([[1, 2, 3, 4, 5, 6, 7, 8]]) 2
tensor([[1, 2, 3, 4, 5, 6, 7, 8]]) 2


In [82]:
t5 = torch.ones(3,4)
print("Org tensor \n", t5)
t6 = torch.flatten(t5)
print("Flattened tensor \n", t6,t6.shape)

t7 = t5.reshape((2,3,2))
print(t7)
print(t7.flatten(0))
print(t7.flatten(1))


Org tensor 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Flattened tensor 
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([12])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [53]:
# Flatten
# torch.flatten(tensor, start_dim=dim, -1) => Provide the starting dimension from where flatten should occur
# This is very useful in CNN output to FCN layers
# If we have [batch_size, channels, width, height], then we can flatten from channel
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

t4 = torch.stack((t1,t2,t3),dim=0)
print(t4, t4.shape)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]]) torch.Size([3, 4, 4])


In [111]:
a = [1,2,3,4,5,6,7,8,9,10]

for i in range(0, len(a), 2):
    print(a[i:i+2])


[1, 2]
[3, 4]
[5, 6]
[7, 8]
[9, 10]


In [116]:
t = torch.tensor([[1,2,3],[4,5,6]])
print("Dim 0 add axis ", t.unsqueeze(dim=0))
print("Dim 1 add axis \n", t.unsqueeze(dim=1))

Dim 0 add axis  tensor([[[1, 2, 3],
         [4, 5, 6]]])
Dim 1 add axis 
 tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


In [128]:
t1 = torch.tensor([[1,2,3],[11,12,13]])
t2 = torch.tensor([[20,30,40],[21,31,41]])

print(t1, t1.shape)
print(t2)


t4 = torch.cat((t1,t2), dim=0)
print("\n Concat along dim  0 \n ", t4, t4.shape)

t5 = torch.cat((t1,t2), dim=1)
print("Concat along dim  1\n ", t5, t5.shape)



tensor([[ 1,  2,  3],
        [11, 12, 13]]) torch.Size([2, 3])
tensor([[20, 30, 40],
        [21, 31, 41]])

 Concat along dim  0 
  tensor([[ 1,  2,  3],
        [11, 12, 13],
        [20, 30, 40],
        [21, 31, 41]]) torch.Size([4, 3])
Concat along dim  1
  tensor([[ 1,  2,  3, 20, 30, 40],
        [11, 12, 13, 21, 31, 41]]) torch.Size([2, 6])


In [123]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.tensor([7,2,3])
print(torch.cat((t1,t2,t3), dim=0))
print(torch.stack((t1,t2,t3), dim=0))
print(torch.stack((t1,t2,t3), dim=1))

tensor([1, 2, 3, 4, 5, 6, 7, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 2, 3]])
tensor([[1, 4, 7],
        [2, 5, 2],
        [3, 6, 3]])


In [ ]:
import tensorflow as tf
print(tf.__version__)